# Generated by Django 4.2.15 on 2026-07-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('LLAMADA', 'Llamada'), ('REUNION', 'Reunión'), ('TAREA', 'Tarea'), ('EMAIL', 'Email')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.account')),
            ],
            options={
                'ordering': ['due_date'],
                'abstract': False,
            },
        ),
    ]
