# Generated by Django 4.2.15 on 2026-07-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pipeline.opportunity'),
        ),
    ]
